### ISSUE TITLE
TypeError: Cannot read property 'forOwn' of undefined when using parse wrapper

### ISSUE THREAD

**Issue by amirbaron** [rafbgarcia/angular-parse-wrapper#9]
```
TypeError: Cannot read property 'forOwn' of undefined
    at module.factory.wrapParse (http://MyAppUrl/components/angular-parse-wrapper/src/parse-wrapper.js:51:8)
    at Object.<anonymous> (http://quiz22.parseapp.com/scripts/models/item.js:3:23)
    at Object.e [as invoke] (http://quiz22.parseapp.com/components/angular/angular.min.js:36:315)
    at Object.$get (http://quiz22.parseapp.com/components/angular/angular.min.js:34:268)
    at Object.e [as invoke] (http://quiz22.parseapp.com/components/angular/angular.min.js:36:315)
    at http://quiz22.parseapp.com/components/angular/angular.min.js:38:110
    at d (http://quiz22.parseapp.com/components/angular/angular.min.js:36:13)
    at e (http://quiz22.parseapp.com/components/angular/angular.min.js:36:283)
    at Object.instantiate (http://quiz22.parseapp.com/components/angular/angular.min.js:36:432)
    at $get (http://quiz22.parseapp.com/components/angular/angular.min.js:76:49) <div ui-view="" class="ng-scope">
```

Does anyone got this error as well?

**Comment by muhammadnasr** [comment]
Yes we got this error.

**Comment by engeshra** [comment]
We have the same error, any update ? @rafbgarcia

**Comment by muhammadnasr** [comment]
@engeshra @amirbaron The error was solved!
 Simply the url for lodash was not correct.
check your includes for lodash
look for something like this in your project
    <script src="bower_components/lodash/dist/lodash.js"></script>

**Comment by amirbaron** [comment]
Thanks!
